### ISSUE TITLE
Dynamic plugin installation fails

### ISSUE THREAD

**Issue by kramtessib** [Praqma/praqma-jenkins-casc#14]
Running with the jenkins4casc:0.7-alpha image and most recent jenkins.yaml fails to start Jenkins with the following error during plugin installation:
`jenkins_1  | java.io.IOException: Failed to dynamically deploy this plugin
jenkins_1  | 	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1893)
jenkins_1  | 	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1651)
jenkins_1  | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
jenkins_1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
jenkins_1  | 	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:112)
jenkins_1  | 	at java.lang.Thread.run(Thread.java:748)
jenkins_1  | Caused by: java.util.zip.ZipException: error in opening zip file`

**Comment by MadsNielsen** [comment]
@kramtessib Yep you're right. I've reverted the update to 0.7-alpha until i figure out what causes this.

**Comment by MadsNielsen** [comment]
@kramtessib Hopefully plugin installation should be possible with the next release. (0.9-alpha). In 0.9-alpha it should work, but we will always require a restart upon plugin updates. Dynamic installation is not really possible currently the way we extract dependencies, when we install a specific version of a plugin.
