### ISSUE TITLE
Jenkins fails to start

### ISSUE THREAD

**Issue by chandanadesilva** [Praqma/praqma-jenkins-casc#19]
I tried this demo today, and Jenkins failed with this error:
To reproduce, on a linux machine, clone this repo, and run docker-compose up --build

`jenkins_1  | io.jenkins.plugins.casc.ConfiguratorException: Invalid configuration elements for type class jenkins.model.GlobalConfigurationCategory$Security : remotingCLI.
jenkins_1  | Available attributes : apiToken, crumb, downloadSettings, envInject, globalJobDslSecurityConfiguration, masterKillSwitchConfiguration, queueItemAuthenticator, sSHD, scriptApproval, updateSiteWarningsConfiguration
jenkins_1  | 	at io.jenkins.plugins.casc.BaseConfigurator.handleUnknown(BaseConfigurator.java:377)
jenkins_1  | 	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:366)
jenkins_1  | 	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:287)
jenkins_1  | 	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$7(ConfigurationAsCode.java:716)
jenkins_1  | 	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:666)
jenkins_1  | Caused: io.jenkins.plugins.casc.ConfiguratorException: security: error configuring 'security' with class io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator configurator
jenkins_1  | 	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:672)
jenkins_1  | 	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:716)
jenkins_1  | 	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:701)
jenkins_1  | 	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:592)
jenkins_1  | 	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:281)
jenkins_1  | 	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:273)
jenkins_1  | Caused: java.lang.reflect.InvocationTargetException
jenkins_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jenkins_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jenkins_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jenkins_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
jenkins_1  | 	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
jenkins_1  | Caused: java.lang.Error
jenkins_1  | 	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
jenkins_1  | 	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
jenkins_1  | 	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1118)
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
jenkins_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jenkins_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jenkins_1  | 	at java.lang.Thread.run(Thread.java:748)
`

**Comment by krish143434** [comment]
any update on this issue, we are also facing the same

**Comment by samp-git18** [comment]
I'm running into the same issue too, any update ?

**Comment by krish143434** [comment]
try this out if its related to you 

https://jenkins.io/doc/upgrade-guide/2.204/#remove-browser-based-metadata-download-settings

**Comment by samp-git18** [comment]
Yup it works, read the doc a while back, downloadSettings is deprecated.
